services:
  postgres:
    image: postgres:16
    container_name: ftpaste_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ftpaste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ftpase-api:
    image: zubula7la7/ftpaste-backend:alpha-1
    container_name: ftpaste_api
    ports:
      - "5044:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ftpaste;Username=postgres;Password=postgres
    depends_on:
      - postgres
    restart: always

  ftpaste-frontend:
    image: zubula7la7/ftpaste-frontend:alpha-1
    container_name: ftpaste_frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://ftpase-api:8080
    depends_on:
      - ftpase-api
    restart: always

volumes:
  postgres_data:
